# Generated by Django 4.2.4 on 2024-04-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0004_alter_mealplan_program'),
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_set', to='meal_plans.mealplan', verbose_name='MealPlan'),
        ),
    ]
