# Generated by Django 4.2.4 on 2024-04-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        ('exercises', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_set', to='workouts.workout', verbose_name='Workout'),
        ),
    ]
